### ISSUE TITLE
How to pass a sentence to word2vec.c

### ISSUE THREAD

**Issue by sujitahirrao** [shaform/experiments#1]
word2vec.c takes train.txt and outputs vocab.txt and vectors.txt which is later used to create sentence_vectors.txt. But I am facing trouble converting my input sentence in vector format by loading the vocab and train files in word2vec.c. Quick reply is appreciated. 

Thanks!

**Comment by shaform** [comment]
Hi sujitahirrao,

If you use this branch https://github.com/shaform/word2vec/tree/doc2vec , then you could use something like:

```
@@SS-1 this is a sentence
@@SS-2 this is a sentence again
@@SS-3 this is a sentence again and again
@@SS-4 this is a sentence again and again and again
```

with word2vec command such as

```
./word2vec  -min-count 1 -train train.txt -output out.txt -sentence-vectors 1
```

and you'll get:

```
@@SS-3 0.001972 -0.000983 ...
@@SS-4 -0.004038 -0.002650 ...

```

**Comment by sujitahirrao** [comment]
Hi shaform,

Thanks for reply.

I am still confused where should I pass

> @@SS-1 this is a sentence
> @@SS-2 this is a sentence again
> @@SS-3 this is a sentence again and again
> @@SS-4 this is a sentence again and again and again

in the word2vec.c. Should I put this in train.txt and then run ./word2vec as you suggested by loading previously created vocab.txt and vectors.txt (created from original train.txt)?

**Comment by shaform** [comment]
Hi @sujitahirrao ,

Unfortunately, this implementation does not support generating sentence vectors from pre-trained word vectors. Instead, you must train the sentence vectors and word vectors together. Therefore, these lines should be put into train.txt. (Actually, if you enable the `-sentence-vectors` switch, every line of train.txt must be prepended with a sentence id.)

This is because that to generate the sentence vectors, we not only need the word embeddings but also  the model weights, but word2vec does not save those weights.

**Comment by sujitahirrao** [comment]
Thanks @shaform . I will try to add the dependencies you mentioned to word2vec and share here if I succeed.
